### ISSUE TITLE
NameError: nane 'InterpolationMode' is not defined

### ISSUE THREAD

**Issue by wyanb** [hmyao22/DADF#1]
Traceback (most recent call last):
File "reconstruction_train.py" , line 6, in <nodule>fron dataset inport TrainData,TestData
File " /media/xpu107/wyb/DADF-main/dataset.py" , line 104，in <nodule>
transform_x = T.Compose([T.Resize(image_size，InterpolationMode.BICUBIC),
NameError: nane 'InterpolationMode' is not defined

Hello, would you like to ask if this reconstructed training can be run?

**Comment by hmyao22** [comment]
> Traceback (most recent call last): File "reconstruction_train.py" , line 6, in fron dataset inport TrainData,TestData File " /media/xpu107/wyb/DADF-main/dataset.py" , line 104，in transform_x = T.Compose([T.Resize(image_size，InterpolationMode.BICUBIC), NameError: nane 'InterpolationMode' is not defined
> 
> Hello, would you like to ask if this reconstructed training can be run?

Hello, the reason for this BUG is that the version of torchvision does not match. Please install version 0.10.1.

**Comment by wyanb** [comment]
I added the following line of code to the dataset.py file.

from torchvision.transforms import Resize,InterpolationMode

 The previous bug disappeared, but the following bug occurred. 

Traceback (most recent call last):
File "reconstruction_train.py" , line 6, in <module>from dataset import TrainData,TestData
File " /media/xpu107/wyb/DADF-main/dataset.py" , line 125, in <module>class TrainData(data.Dataset):
NameError: name 'data' is not defined

**Comment by hmyao22** [comment]
> I added the following line of code to the dataset.py file.
> 
> from torchvision.transforms import Resize,InterpolationMode
> 
> The previous bug disappeared, but the following bug occurred.
> 
> Traceback (most recent call last): File "reconstruction_train.py" , line 6, in from dataset import TrainData,TestData File " /media/xpu107/wyb/DADF-main/dataset.py" , line 125, in class TrainData(data.Dataset): NameError: name 'data' is not defined

please add :import torch.utils.data as data

**Comment by wyanb** [comment]
Thank you very much, the following is a new bug.
Traceback (most recent call last):
File "reconstruction_train.py" , line 12, in <module>
fron Models.misc import NativescalerwithGradNormCount as NativescalerFile "/media/xpu107/wyb/DADF-main/Models/misc.py", line 21,in <module>fron torch._six import inf
ModuleNotFoundError: No module named 'torch._six'

I would like to ask, besides lowering the torch version, is there any other way to fix this bug?

**Comment by wyanb** [comment]
I commented out the line "from torch._six import inf", hoping it would not affect subsequent code.

**Comment by wyanb** [comment]
And need to modify line 288 of the misc.py file
if norm_type == float( 'inf ' ):

**Comment by wyanb** [comment]
training_dataset:tile
cuda:3
/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/torchvision/models/_utils.py:135: UserWarning: Using 'weights' as positional parameter(s) is deprecated since 0.13 and may be removed in the future. Please use keyword parameter(s) instead.
  warnings.warn(
/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet34_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet34_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
load weights!
/media/xpu107/wyb/UniAD-main/data/MVTec-AD/mvtec_anomaly_detection/tile/train
 96%|█████████████████████████████████████████▍ | 27/28 [00:11<00:00,  3.08it/s][0]  F_loss: 0.055
100%|███████████████████████████████████████████| 28/28 [00:12<00:00,  2.32it/s]
Traceback (most recent call last):
  File "reconstruction_train.py", line 160, in <module>
    Rec_train(opt)
  File "reconstruction_train.py", line 105, in Rec_train
    plt.savefig('feature/' + str(epoch) + '.png')
  File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1023, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/PIL/Image.py", line 2410, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'feature/0.png'

Currently, the show_feature_map parameter is changed from true to false, so it can be trained. But is there any other solution to this bug?

**Comment by hmyao22** [comment]
> training_dataset:tile cuda:3 /home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/torchvision/models/_utils.py:135: UserWarning: Using 'weights' as positional parameter(s) is deprecated since 0.13 and may be removed in the future. Please use keyword parameter(s) instead. warnings.warn( /home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet34_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet34_Weights.DEFAULT` to get the most up-to-date weights. warnings.warn(msg) load weights! /media/xpu107/wyb/UniAD-main/data/MVTec-AD/mvtec_anomaly_detection/tile/train 96%|█████████████████████████████████████████▍ | 27/28 [00:11<00:00, 3.08it/s][0] F_loss: 0.055 100%|███████████████████████████████████████████| 28/28 [00:12<00:00, 2.32it/s] Traceback (most recent call last): File "reconstruction_train.py", line 160, in Rec_train(opt) File "reconstruction_train.py", line 105, in Rec_train plt.savefig('feature/' + str(epoch) + '.png') File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1023, in savefig res = fig.savefig(*args, **kwargs) File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/figure.py", line 3378, in savefig self.canvas.print_figure(fname, **kwargs) File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure result = print_method( File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2232, in print_method = functools.wraps(meth)(lambda *args, **kwargs: meth( File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png self._print_pil(filename_or_obj, "png", pil_kwargs, metadata) File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil mpl.image.imsave( File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/matplotlib/image.py", line 1689, in imsave image.save(fname, **pil_kwargs) File "/home/xpu107/下载/yes/envs/wyblib/lib/python3.8/site-packages/PIL/Image.py", line 2410, in save fp = builtins.open(filename, "w+b") FileNotFoundError: [Errno 2] No such file or directory: 'feature/0.png'
> 
> Currently, the show_feature_map parameter is changed from true to false, so it can be trained. But is there any other solution to this bug?

Please create a subfolder named feature under the project folder

**Comment by wyanb** [comment]
Thank you very much for your guidance.
