### ISSUE TITLE
No module named 'reconstruction_dataset'

### ISSUE THREAD

**Issue by wyanb** [hmyao22/DADF#2]
Traceback (most recent call last):
File "/media/xpu107/wyb/DADF-main/fuse_main.py",line 11, in <module>
from reconstruction_dataset import denormalize
MaduleNotFoundError: No module named 'reconstruction_dataset'

Hello, may I ask if you uploaded one less file?

**Comment by hmyao22** [comment]
Please delete it, we're sorry we weren't organized well enough for the project

**Comment by hmyao22** [comment]
> Traceback (most recent call last): File "/media/xpu107/wyb/DADF-main/fuse_main.py",line 11, in from reconstruction_dataset import denormalize MaduleNotFoundError: No module named 'reconstruction_dataset'
> 
> Hello, may I ask if you uploaded one less file?

If you are interested, please add my WeChat and other contact information through my email yhm22@mails.tsinghua.edu.cn
